services:
  nginx-server:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html # can update content to '.../public' folder from web
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/conf.d/default.bak.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - mysql
  php-fpm:
    build: 
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:5.7
    env_file:
      - ./mysql/.env
  composer-util:
    build:
      dockerfile: ./composer/Dockerfile
    volumes:
      - ./src:/var/www/html
  artisan-util:
    build: 
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "php", "/var/www/html/artisan" ]
  npm-util:
    image: node:18
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html
